---
version: '3'
services:
  app:
    build: "."
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
    - ".:/app"
    ports:
    - 3000:3000
    stdin_open: true
    tty: true
    depends_on:
    - db
    - redis
    links:
    - db
    environment:
      REDIS_URL: redis://redis:6379/0
      RAILS_ENV: development
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: postgres
      DATABASE_HOST: db
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres_app_development
    ports:
      - 5432:5432
  redis:
    image: redis:7.2
    ports:
      - 6379:6379

